"""Create base models

Revision ID: 40811aeccb86
Revises: 
Create Date: 2025-05-27 18:33:48.200807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40811aeccb86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dojo', sa.String(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['samurais.id'], name=op.f('fk_clans_leader_id_samurais')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dojo', name='unique_dojo_name'),
    sa.UniqueConstraint('leader_id', name='unique_leader_id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('bushido_reward', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samurais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('bushido', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], name=op.f('fk_samurais_clan_id_clans')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_held', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('bushido_wagered', sa.Integer(), nullable=True),
    sa.Column('challenger_id', sa.Integer(), nullable=True),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenger_id'], ['samurais.id'], name=op.f('fk_duels_challenger_id_samurais')),
    sa.ForeignKeyConstraint(['opponent_id'], ['samurais.id'], name=op.f('fk_duels_opponent_id_samurais')),
    sa.ForeignKeyConstraint(['winner_id'], ['samurais.id'], name=op.f('fk_duels_winner_id_samurais')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('bushido_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('samurai_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['samurai_id'], ['samurais.id'], name=op.f('fk_weapons_samurai_id_samurais')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapons')
    op.drop_table('duels')
    op.drop_table('samurais')
    op.drop_table('quests')
    op.drop_table('clans')
    # ### end Alembic commands ###
