"""Add leader_id column to clan

Revision ID: 5713b16da4f1
Revises: 62733d57fcbc
Create Date: 2025-05-29 06:02:43.980636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5713b16da4f1'
down_revision: Union[str, None] = '62733d57fcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('leader_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clans', 'leader_id')
    # ### end Alembic commands ###
