"""Create relationships

Revision ID: 6dbe64806086
Revises: 40811aeccb86
Create Date: 2025-05-27 21:24:17.421106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbe64806086'
down_revision: Union[str, None] = '40811aeccb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samurai_quest',
    sa.Column('samurai_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_samurai_quest_quest_id_quests')),
    sa.ForeignKeyConstraint(['samurai_id'], ['samurais.id'], name=op.f('fk_samurai_quest_samurai_id_samurais')),
    sa.PrimaryKeyConstraint('samurai_id', 'quest_id')
    )
    op.drop_column('samurais', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samurais', sa.Column('rank', sa.VARCHAR(), nullable=True))
    op.drop_table('samurai_quest')
    # ### end Alembic commands ###
